### ISSUE TITLE
NodeMailer

### ISSUE THREAD

**Issue by ashish13377** [ashish13377/paving-plus#2]
How to add nodemailer in app,js

**Comment by PavingPlus** [comment]
First, you to install a Nodemailer in-app using
npm i nodemailer

after that import Nodemailer
const nodemailer = require("nodemailer")

after that, you need to add this

[app.post](http://app.post/)("/contact/send-mail", (req, res) => {
const { fullName, email, phone, message } = req.body;

const output = <h4> Contact us for detail. </h4> <br /> <p><strong>Name : </strong> ${fullName}</p> <p><strong>Email : </strong> ${email}</p> <p><strong>Phone : </strong> ${phone}</p> <p><strong>Message : </strong> ${message}</p> <br /> <br /> <p>Thank you</p>

let transporter = nodemailer.createTransport({
host: "[smtp.gmail.com](http://smtp.gmail.com/)",
port: 587,
secure: false, // true for 465, false for other ports
auth: {
user: "", // generated ethereal user
pass: "", // generated ethereal password
},
});

let mailOption = {
from: '', // sender address
to: '', // list of receivers
subject: "", // Subject line
text: "", // plain text body
html: output, // HTML body
}

// send mail with defined transport object
transporter.sendMail(mailOption, (error, info) => {
if (error) {
res.json(error)
} else {
const data = info.messageId;
res.json({ message: "Message sent", data })
}
});
})

**Comment by ashish13377** [comment]
Thanks Sir
